### ISSUE TITLE
Thank you for this... 

### ISSUE THREAD

**Issue by ChriStef** [Paul-Browne/lazyestload.js#1]
... Well done seams very good.

What is the browsers support? 

Please advise how to make image placeholders what size and quality etc. Some tips or auto scripts you know php?

Thank you again for this. I will try it.

**Comment by ucffool** [comment]
**Desktop**: Current Firefox, Chrome, and Edge seem to be working fine.

**Comment by Paul-Browne** [comment]
Browser Compatibility is pretty solid, basically any browser that can handle the following

| Method | IE version |
|--|--|
| `getBoundingClientRect` | 4 |
| `querySelectorAll` | 8 |
| `addEventListener ` | 9 |
| `classList` | 10 |

If you need to support IE9 then you could polyfill the classList API. But IMO you shouldn't be supporting browsers that old.

In regards to making the placeholders I use node.
I'm not sure how familiar you are with node but here's a snippet from my build process that creates the placeholders

```js
var gulp         = require('gulp');
var changed      = require('gulp-changed');
var image        = require('gulp-image');
var imageResize  = require('gulp-image-resize');

var imgPrefs = {
    pngquant: true,
    optipng: false,
    zopflipng: true,
    jpegRecompress: false,
    mozjpeg: true,
    guetzli: false,
    gifsicle: false,
    svgo: true,
    concurrent: 10
};

gulp.task('placeholderImages', function() {
  return gulp.src('src/images/**/*.{jpg,jpeg,png,gif}')
    .pipe(changed('dist/images/placeholders'))    
    .pipe(imageResize({
      noProfile: true,
      width : 40,
      quality: 0
    }))
    .pipe(image(imgPrefs))
    .pipe(gulp.dest('dist/images/placeholders'))
})
```

Ideally they should be less than 1kb, between 40 and 50 pixels wide and have the same aspect ratio as the image that will be replacing it.
