### ISSUE TITLE
Working with "data-srcset" -> data-srcset broken?

### ISSUE THREAD

**Issue by NilsDannemann** [Paul-Browne/lazyestload.js#9]
Hi there,

phenomenal work. 

I'm struggling to get responsive images with srcset to work.
The data-srcset breaks for me.

Getting the following error:
![image](https://user-images.githubusercontent.com/1572663/44981001-a76e7780-af71-11e8-9800-2339fda702a6.png)

Anyone experiencing the same issue?

Code:

`<img class="lazyestload" src="images/imagethumb.jpg" data-srcset="images/image1.jpg 1x, images/image2.jpg 2x" >`

**Comment by englishextra** [comment]
@Paul-Browne `data-srcset` should be `data-src`

**Comment by NilsDannemann** [comment]
Just to clarify:
I'm trying to get the responsive image solution to work. 

As the readme says to use "data-srcset" like so: 
`<img class="lazyestload" src="images/placeholder/sunset.jpg" data-srcset="images/sunset-1x.jpg 1x, images/sunset-2x.jpg 2x, images/sunset-3x.jpg 3x" >`

I'm getting an error with this, resulting in a src="null" on the image and the error above.

The basic usecase with "data-src" is working for me:
`<img class="lazyestload" src="images/placeholder/sunset.jpg" data-src="images/sunset.jpg" >`

**Comment by NilsDannemann** [comment]
Hi Paul,

just to clarify:
I'm trying to get the responsive image solution to work.

As the readme says to use "data-srcset" like so:
"<img class="lazyestload" src="images/placeholder/sunset.jpg"
data-srcset="images/sunset-1x.jpg 1x, images/sunset-2x.jpg 2x,
images/sunset-3x.jpg 3x" >"

I'm getting an error with this, resulting in a src="null" on the image and
the error above.

The basic usecase with "data-src" is working for me:
<img class="lazyestload" src="images/placeholder/sunset.jpg"
data-src="images/sunset.jpg" >

Kind Regards,
Nils

**Comment by englishextra** [comment]
@NilsDannemann I guess everyone is waiting for some jsbin/codepen link from you.

**Comment by NilsDannemann** [comment]
Okay, issue closed. I didn't see that there was an update for the responsive image solution and was still running the old version. Sorry for the troubles.

**Comment by Paul-Browne** [comment]
@NilsDannemann No probs, glad you could close your own ticket 😄
